-- deobf by https://discord.gg/ck3k7nAVS

local UIScale = Instance.new("UIScale")
UIScale.Scale = 0.5
UIScale.Parent = Frame3
local UISizeConstraint = Instance.new("UISizeConstraint")
UISizeConstraint.MinSize = Vector2.new(19, 38)
UISizeConstraint.MaxSize = Vector2.new(2508, 4528)
UISizeConstraint.Parent = Frame3
local UISizeConstraint2 = Instance.new("UISizeConstraint")
UISizeConstraint2.MinSize = Vector2.new(14, 31)
UISizeConstraint2.MaxSize = Vector2.new(2592, 3920)
UISizeConstraint2.Parent = Frame4
local UIScale2 = Instance.new("UIScale")
UIScale2.Scale = 1.4375
UIScale2.Parent = Frame4
local UIPadding = Instance.new("UIPadding")
UIPadding.PaddingTop = UDim.new(0.75, 14)
UIPadding.PaddingBottom = UDim.new(1, 7)
UIPadding.PaddingLeft = UDim.new(0.625, 13)
UIPadding.PaddingRight = UDim.new(0, 18)
UIPadding.Parent = Frame4
local TextLabel = Instance.new("TextLabel")
TextLabel.Position = UDim2.new(1.96875, 83, 0.8125, 122)
TextLabel.Size = UDim2.new(1, 34, 0.25, 20)
TextLabel.AnchorPoint = Vector2.new(0.5, 0.125)
TextLabel.LayoutOrder = 9
TextLabel.Rotation = -476
TextLabel.Parent = Frame3
local UISizeConstraint3 = Instance.new("UISizeConstraint")
UISizeConstraint3.MinSize = Vector2.new(18, 31)
UISizeConstraint3.MaxSize = Vector2.new(3025, 2212)
UISizeConstraint3.Parent = Frame6
local UIPadding2 = Instance.new("UIPadding")
UIPadding2.PaddingTop = UDim.new(0.5, 11)
UIPadding2.PaddingBottom = UDim.new(0.53125, 7)
UIPadding2.PaddingLeft = UDim.new(0.75, 5)
UIPadding2.PaddingRight = UDim.new(1, 13)
UIPadding2.Parent = Frame6
